# Generated by Django 2.2.5 on 2021-02-18 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment_type',
            fields=[
                ('idcomment_type', models.AutoField(primary_key=True, serialize=False)),
                ('description_text', models.CharField(max_length=100)),
                ('date_created', models.DateField(null=True)),
                ('date_modified', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('idcustomer', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('date_created', models.DateField()),
                ('date_modified', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='project_type',
            fields=[
                ('idproject_type', models.AutoField(primary_key=True, serialize=False)),
                ('description_text', models.CharField(max_length=100)),
                ('date_created', models.DateField()),
                ('date_modified', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='resource',
            fields=[
                ('idresource', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateField()),
                ('date_modified', models.DateField()),
                ('date_deleted', models.DateField(null=True)),
                ('ldap', models.CharField(max_length=100, null=True)),
                ('active', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='resource_type',
            fields=[
                ('idresource_type', models.AutoField(primary_key=True, serialize=False)),
                ('description_text', models.CharField(max_length=100)),
                ('date_created', models.DateField()),
                ('date_modified', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='task_status',
            fields=[
                ('idproject_type', models.AutoField(primary_key=True, serialize=False)),
                ('description_text', models.CharField(max_length=100)),
                ('date_created', models.DateField()),
                ('date_modified', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='task_type',
            fields=[
                ('idtask_type', models.AutoField(primary_key=True, serialize=False)),
                ('description_text', models.CharField(max_length=250)),
                ('average_time', models.IntegerField(null=True)),
                ('date_created', models.DateField()),
                ('date_modified', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('idtask', models.AutoField(primary_key=True, serialize=False)),
                ('main_title', models.CharField(max_length=250)),
                ('date_created', models.DateField(null=True)),
                ('date_modified', models.DateField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('commit_date', models.DateField(null=True)),
                ('idresource', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team_management.resource')),
                ('idtask_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team_management.task_status')),
                ('idtask_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team_management.task_type')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='idresource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team_management.resource_type'),
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('idproject', models.AutoField(primary_key=True, serialize=False)),
                ('description_text', models.CharField(max_length=250)),
                ('date_created', models.DateField()),
                ('date_modified', models.DateField()),
                ('idcostumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team_management.customer')),
                ('idproject_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team_management.project_type')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('idcomment', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField(null=True)),
                ('date_created', models.DateField(null=True)),
                ('date_modified', models.DateField(null=True)),
                ('idcomment_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team_management.comment_type')),
            ],
        ),
        migrations.CreateModel(
            name='project_has_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idproject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team_management.project')),
                ('idtask', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team_management.task')),
            ],
            options={
                'unique_together': {('idproject', 'idtask')},
            },
        ),
    ]
