# Generated by Django 2.2.5 on 2021-02-18 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_has_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcomment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team_management.comments')),
                ('idtask', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team_management.task')),
            ],
            options={
                'unique_together': {('idcomment', 'idtask')},
            },
        ),
    ]
