# Generated by Django 2.2.5 on 2021-02-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0003_auto_20210218_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_type',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resource_type',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task_status',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task_type',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
